<?php

/**
 * @file
 * Contains commerce_payway_net.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_payway_net_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_payway_net module.
    case 'help.page.commerce_payway_net':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pay by credit card via Westpac PayWay Net') . '</p>';
      return $output;

    default:
  }
}
